### PR TITLE
fix typo on line 373 of resource_connection.go

### PR DESCRIPTION
**Pull request by jbennett7**
Fix typo
https://github.com/hirosassa/terraform-provider-looker/blob/89a1ec42026600176be2843b77727b352030e327/pkg/looker/resource_connection.go#L373

### CODE REVIEW

**Comment by hirosassa** [comment]
hmmm, lint is failed. I'll take a closer look.

**Comment by jbennett7** [comment]
There is another typo on Line 176 of the same file when using pdt_context_override block:
https://github.com/hirosassa/terraform-provider-looker/blob/89a1ec42026600176be2843b77727b352030e327/pkg/looker/resource_connection.go#L176

Should I add the fix to that to this PR?

**Comment by hirosassa** [comment]
@jbennett7 Thanks! Let's fix it in this PR too.

**Comment by jbennett7** [comment]
Fixed typo in the documentation as well: `docs/resources/connection.md`

**Comment by hirosassa** [comment]
@jbennett7 Sorry for massively late reply. I fixed CI in https://github.com/hirosassa/terraform-provider-looker/pull/50.
Cloud you please rebase current master?
I'll merge this PR after rebase.

**Comment by hirosassa** [comment]
Looks good! I'll merge this. @jbennett7 Thanks for your contribution and patience.

**Comment by hirosassa** [comment]
@jbennett7 Thanks again! I released new version of this provider.
https://github.com/hirosassa/terraform-provider-looker/releases/tag/v0.9.0

**Pull request merged**
